title: scaralbi
email: scaralbi.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Modus et Ordo
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
