baseURL = "https://scaralbi.github.io/"
languageCode = "en-us"
title = "scaralbi"

[permalinks]
  posts = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 4
  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 5